// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqvlzZ-CLQ1mbWlME2FlwTnyyz2Q5BfkA',
    appId: '1:293168584491:web:24cdc81c58737a305b576e',
    messagingSenderId: '293168584491',
    projectId: 'finalproject-38566',
    authDomain: 'finalproject-38566.firebaseapp.com',
    storageBucket: 'finalproject-38566.firebasestorage.app',
    measurementId: 'G-L98V73FZM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkg7sUdr6IIVnW3qD88PXRlXFoHl2tJUc',
    appId: '1:293168584491:android:ea0db88b153296325b576e',
    messagingSenderId: '293168584491',
    projectId: 'finalproject-38566',
    storageBucket: 'finalproject-38566.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1KcCXQg7I8cqHXtggbWJepudPdptDXaY',
    appId: '1:293168584491:ios:ef3b9aa3a58aa5d65b576e',
    messagingSenderId: '293168584491',
    projectId: 'finalproject-38566',
    storageBucket: 'finalproject-38566.firebasestorage.app',
    iosBundleId: 'edu.umn.d.cs3541.team4.GetInGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1KcCXQg7I8cqHXtggbWJepudPdptDXaY',
    appId: '1:293168584491:ios:ef3b9aa3a58aa5d65b576e',
    messagingSenderId: '293168584491',
    projectId: 'finalproject-38566',
    storageBucket: 'finalproject-38566.firebasestorage.app',
    iosBundleId: 'edu.umn.d.cs3541.team4.GetInGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqvlzZ-CLQ1mbWlME2FlwTnyyz2Q5BfkA',
    appId: '1:293168584491:web:29892001e92be72b5b576e',
    messagingSenderId: '293168584491',
    projectId: 'finalproject-38566',
    authDomain: 'finalproject-38566.firebaseapp.com',
    storageBucket: 'finalproject-38566.firebasestorage.app',
    measurementId: 'G-C8KJEE3YLV',
  );
}